In [1]:
import pandas as pd, numpy as np
data = pd.read_csv('D:\hanny\DSU\Bot Twitter.csv')
data.head(10)

ID  Screen name  Foto Profil  Following  Following kurang 30  \
0  1,32E+22            1            0         53                    0   
1  1,32E+23            1            0        218                    0   
2  1,33E+23            1            0        530                    0   
3  1,33E+23            1            1        237                    0   
4  1,35E+23            1            0         94                    0   
5  1,34E+23            1            0        631                    0   
6  1,34E+23            0            1        513                    0   
7  1,33E+23            0            0         88                    0   
8  1,33E+23            1            1        463                    0   
9  1,26E+23            0            1         53                    0   

   Followers  Followers lebih 1000  Tweet  Tweet kurang 50  Lokasi  ...  \
0         25                     0      3                1       1  ...   
1         52                     0      3                1       1  ...   
2        123                     0      5                1       1  ...   
3         18                     0      6                1       1  ...   
4         31                     0     14                1       1  ...   
5       1858                     1   1001                0       1  ...   
6        493                     0    168                0       1  ...   
7         42                     0     14                1       0  ...   
8       7893                     0    327                0       1  ...   
9      46819                     1     43                0       1  ...   

   Follower Ratio 2:1  Follower Ratio 50:1  Follower Ratio 100:1  \
0                   1                    0                     0   
1                   0                    0                     0   
2                   0                    0                     0   
3                   0                    0                     0   
4                   0                    0                     0   
5                   0                    0                     0   
6                   0                    0                     0   
7                   1                    0                     0   
8                   0                    0                     0   
9                   0                    0                     0   

   Pola Aktivitas Akun  Usia Akun (bulan)  Usia Akun kurang sama dengan 12  \
0                    1                  0                                1   
1                    0                  0                                1   
2                    0                  0                                1   
3                    1                  0                                1   
4                    1                  0                                1   
5                    0                  0                                1   
6                    0                  0                                1   
7                    0                  0                                1   
8                    1                  0                                1   
9                    1                  0                                1   

   Rataan Tweet per Minggu  Retweet Ratio %  \
0                     0.29               33   
1                     0.25                0   
2                     0.65                0   
3                     0.77                0   
4                  3700.00               86   
5                   310.00                1   
6                    72.00               45   
7                     2.20                0   
8                    24.00               95   
9                     0.97               66   

   Retweet Ratio lebih sama dengan 60  Kategori  
0                                   0         1  
1                                   0         0  
2                                   0         0  
3                                   1         1  
4  

In [2]:
data.shape

(2000, 22)

In [3]:
data.isnull().sum()

ID                                    0
Screen name                           0
Foto Profil                           0
Following                             0
Following kurang 30                   0
Followers                             0
Followers lebih 1000                  0
Tweet                                 0
Tweet kurang 50                       0
Lokasi                                0
URL                                   0
Deskripsi                             0
Follower Ratio 2:1                    0
Follower Ratio 50:1                   0
Follower Ratio 100:1                  0
Pola Aktivitas Akun                   0
Usia Akun (bulan)                     0
Usia Akun kurang sama dengan 12       0
Rataan Tweet per Minggu               0
Retweet Ratio %                       0
Retweet Ratio lebih sama dengan 60    0
Kategori                              0
dtype: int64

In [4]:
data.Kategori.value_counts()

0    1000
1    1000
Name: Kategori, dtype: int64

In [5]:
fitur= data.iloc[:, 1:21].values

In [6]:
fitur[0]

array([ 1.  ,  0.  , 53.  ,  0.  , 25.  ,  0.  ,  3.  ,  1.  ,  1.  ,
        0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  1.  ,  0.29,
       33.  ,  0.  ])

In [7]:
label = data.iloc[:, 21:22].values

In [8]:
label

array([[1],
       [0],
       [0],
       ...,
       [0],
       [1],
       [0]], dtype=int64)

In [9]:
from sklearn.model_selection import train_test_split
fitur_train, fitur_test, label_train, label_test = train_test_split(fitur, label, random_state= 0, test_size= 0.20)

In [10]:
len(fitur_train)

1600

In [11]:
len(fitur_test)

400

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
fitur_train = sc.fit_transform(fitur_train)
fitur_test= sc.transform(fitur_test)

In [15]:
#svm linear
from sklearn.svm import SVC
svm = SVC(kernel = 'linear')
svm.fit(fitur_train, label_train)
svm_predict = svm.predict(fitur_test)

#membuat confussion matriks dan menghitung akurasi,presisi,recall,f1score
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.metrics import accuracy_score
print('Akurasi = ', accuracy_score(label_test, svm_predict))
print(confusion_matrix(label_test, svm_predict))
print(classification_report(label_test, svm_predict))

Akurasi =  0.8175
[[161  42]
 [ 31 166]]
              precision    recall  f1-score   support

           0       0.84      0.79      0.82       203
           1       0.80      0.84      0.82       197

    accuracy                           0.82       400
   macro avg       0.82      0.82      0.82       400
weighted avg       0.82      0.82      0.82       400



C:\Users\Aarifinn\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [17]:
#naivebayes
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(fitur_train, label_train)
gnb_predict = gnb.predict(fitur_test)

print('Akurasi = ', accuracy_score(label_test, gnb_predict))
print(confusion_matrix(label_test, gnb_predict))
print(classification_report(label_test, gnb_predict))

Akurasi =  0.5825
[[199   4]
 [163  34]]
              precision    recall  f1-score   support

           0       0.55      0.98      0.70       203
           1       0.89      0.17      0.29       197

    accuracy                           0.58       400
   macro avg       0.72      0.58      0.50       400
weighted avg       0.72      0.58      0.50       400



C:\Users\Aarifinn\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [18]:
from sklearn import tree
DT = tree.DecisionTreeClassifier()
DT.fit(fitur_train, label_train)
DT_predict = DT.predict(fitur_test)

print('Akurasi = ', accuracy_score(label_test, DT_predict))
print(confusion_matrix(label_test, DT_predict))
print(classification_report(label_test, DT_predict))

Akurasi =  0.85
[[171  32]
 [ 28 169]]
              precision    recall  f1-score   support

           0       0.86      0.84      0.85       203
           1       0.84      0.86      0.85       197

    accuracy                           0.85       400
   macro avg       0.85      0.85      0.85       400
weighted avg       0.85      0.85      0.85       400

